version: '3'

services:
  spring:
    container_name: spring
    image: remmo1/currency-converter-spring:latest
    ports:
      - '8080:8080'
    environment:
      FRONTEND.ADDRESS: http://react:3000

  react:
    container_name: react
    image: remmo1/currency-converter-react
    ports:
      - '3000:3000'
    environment:
      REACT_APP_BACKEND_URL: http://spring:8080/exchange
