apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-deployment
  labels:
    app: react-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
      - name: react
        image: remmo1/currency-converter-react
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: react-config-map
              key: backendAddress
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |
    upstream Backend {
      server spring:8080;
    }
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://localhost:8099;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: react-nginx-service
spec:
  type: NodePort
  selector:
    app: react-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30300
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  selector:
    app: react-nginx
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30301
